Ecommerceproject/Controllers/ContactController.cs
using Ecommerceproject.Services.DatabaseServices;
using Ecommerceproject.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerceproject.Controllers
{
    public class ContactController : Controller
    {
        #region
        private readonly ContactFormDbServices _contactService;
        public ContactController(ContactFormDbServices dbServices)
        {
            _contactService = dbServices;
        }
        #endregion
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactUsFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _contactService.AddContactFormAsync(model);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Please fill in all the required fields");
            return View(model);
        }
    }
}

Ecommerceproject/Controllers/ProductsController.cs
using Ecommerceproject.Models;
using Ecommerceproject.Services.DatabaseServices;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerceproject.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductDbServices _productService;
        public ProductsController(ProductDbServices productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<ProductModel> model = await _productService.GetAllAsync();
            return View(model);
        }


        //Redirects to the details page of the selected product
        [HttpGet]
        public async Task<IActionResult> Details(Guid articlenumber) 
        {
            var result = await _productService.GetOneAsync(articlenumber);

            if (result != null) 
            {
                return View(result);
            }


            return RedirectToAction("Index");
        }
    }
}

Ecommerceproject/Controllers/SignInController.cs
using Ecommerceproject.Services;
using Ecommerceproject.Services.DatabaseServices.AuthenticationServices;
using Ecommerceproject.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerceproject.Controllers;

public class SignInController : Controller
{
    #region
    private readonly AuthenticationDbService _authServices;

    public SignInController(AuthenticationDbService authServices)
    {
        _authServices = authServices;
    }
    #endregion

    //SignIn
    #region
    public IActionResult Index()
    {
        
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Index(SigninViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (await _authServices.LoginAsync(model))
                return RedirectToAction("Index", "Home");
        }
        ModelState.AddModelError("", "Incorrect email or password");
        return View(model);
    }
    #endregion

    //Registration
    #region
    public IActionResult Registration()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Registration(RegistrationViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (await _authServices.UserExistsAsync(x => x.Email == model.Email))
            {
                ModelState.AddModelError("", "A user with the same email already exists");
            }
            if (await _authServices.RegisterAsync(model))
            {
                return RedirectToAction("Index");
            }                
        }
        return View(model);
    }
    #endregion

}

Ecommerceproject/Views/PartialViews/_BestCollection.cshtml
@model List<ProductModel>

<div class="container best-collection ">
    <h1>Best Collection</h1>
    <p class="categories">All ⁄ Bags ⁄ Dress ⁄ Decoration ⁄ Essentials ⁄ Interior ⁄ Laptop ⁄ Mobile ⁄ Beauty</p>
    <section class="productcards">

        @foreach (var product in Model)
        {
            <partial name="/Views/PartialViews/Components/ProductCards/_ProductCardSmall.cshtml" model="product" />
        }
    </section>
    <button class="btn-theme load-btn">
        LOAD MORE
        <i class="fa-solid fa-arrow-rotate-right"></i>
    </button>
</div>

Ecommerceproject/Views/PartialViews/_Footer.cshtml
<footer class="footer">
    <p>© 2023 bmarketo.  All right reserved.</p>
</footer>

Ecommerceproject/Views/PartialViews/_Header.cshtml
<div class="header ">
    <span class="header-text">
        <h5>WELCOME TO BMARKETO SHOP</h5>
        <h1>Exclusive Chair gold Collection.</h1>
        <button class="btn-theme">SHOP NOW</button>
    </span>
    <img src="" alt="">         
</div>

Ecommerceproject/Views/PartialViews/_Navbar.cshtml
<!-- Navbar -->
<header class="container">
    <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img src="/Images/Logo.svg" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto ">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            HOME
                        </a>
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">ADMIN</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Products" asp-action="Index">PRODUCTS</a>
                        }

                    </li>
                    <li class="nav-item" >
                        <a class="nav-link" asp-controller="Contact" asp-action="Index">CONTACT</a>
                    </li>
                    <li class="nav-item">
                        <form>
                            <input id="navbar-search" class="" onclick="">
                            <button class="navbar-search-btn" onclick="expand()" type="button">
                                <i class="bi bi-search"></i>
                            </button>
                            
                        </form>                        
                    </li>
                    <li class="nav-item">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <a class="nav-link" asp-controller="Account" asp-action="Index">MY ACCOUNT</a>
                            <a class="nav-link" asp-controller="SignOut" asp-action="Index">LOGOUT</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="SignIn" asp-action="Index">LOGIN</a>
                        }
                        
                    </li>
                    <li>
                        <a href="">
                            <i class="fa-solid fa-cart-shopping position-relative">
                                <span class="position-absolute translate-middle badge rounded-pill">
                                    10
                                    <span class="visually-hidden">Items in cart</span>
                                </span>
                            </i>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>

Ecommerceproject/Views/PartialViews/_ProductsCarousel.cshtml
@model List<ProductModel>


<div class="top-sellers-carousel">
    <h1>Top selling products in this week</h1>
    <section class="productcards">
        @foreach (var product in Model)
        {
            <partial name="/Views/PartialViews/Components/ProductCards/_ProductCardSmall.cshtml" model="product" />
        }
    </section>
    <span class="navigate-buttons">
        <button><i class="fa-solid fa-angle-left"></i></i></button>
        <button><i class="fa-solid fa-angle-right"></i></button>
    </span>
    <div class="container lower-products">
        <div class="card">
            <img src="https://cdn.pixabay.com/photo/2015/01/21/14/14/apple-606761_1280.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Table lamp 1562 LTG modal</h5>
                <p class="description">
                    Best dress for everyone ed totam velit risus viverra
                    nobis donec recusandae perspiciatis incididuno
                </p>
                <span>
                    <p class="card-text">POST BY: ADMIN</p>
                    <p class="card-text">COMMENTS: 13</p>
                </span>
            </div>
        </div>

        <div class="card">
            <img src="https://cdn.pixabay.com/photo/2015/01/21/14/14/apple-606761_1280.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Table lamp 1562 LTG modal</h5>
                <p class="description">
                    Best dress for everyone ed totam velit risus viverra
                    nobis donec recusandae perspiciatis incididuno
                </p>
                <span>
                    <p class="card-text">POST BY: ADMIN</p>
                    <p class="card-text">COMMENTS: 13</p>
                </span>
            </div>
        </div>

        <div class="card">
            <img src="https://cdn.pixabay.com/photo/2015/01/21/14/14/apple-606761_1280.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Table lamp 1562 LTG modal</h5>
                <p class="description">
                    Best dress for everyone ed totam velit risus viverra
                    nobis donec recusandae perspiciatis incididuno
                </p>
                <span>
                    <p class="card-text">POST BY: ADMIN</p>
                    <p class="card-text">COMMENTS: 13</p>
                </span>
            </div>
        </div>
    </div>
</div>

Ecommerceproject/Views/PartialViews/_Sales.cshtml
@model List<ProductModel>


<div class="main-sales ">
    <div class="container">

        @if (Model.Count > 0)
        {
            <partial name="/Views/PartialViews/Components/ProductCards/_ProductCardMedium.cshtml" model="Model[0]" />
        }

        <div class="card info-card">
            <h6>UP TO SELL</h6>
            <h1>50% OFF</h1>
            <h5>Get The Best Price</h5>
            <p>Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki</p>
            <a href="">Discover More</a>
        </div>

        @if (Model.Count > 1)
        {
            <partial name="/Views/PartialViews/Components/ProductCards/_ProductCardMedium.cshtml" model="Model[1]" />
        }
    </div>
</div>

Ecommerceproject/Views/PartialViews/_SubscribeBar.cshtml
<!-- Subscripe section -->
<div class="subscribe">
    <img src="https://cdn.pixabay.com/photo/2017/08/01/09/02/computer-2563737_1280.jpg" alt="">
    <div class="container">
        <form action="">
            <input type="text" class="subscribe-input" placeholder="Enter your mail here"> 

            <button>SUBSCRIBE FOR NEWSLETTER</button>
        </form>
    </div>

</div>